"""Add is_admin field to User model

Revision ID: 939e613fc2f4
Revises: aead1aa38ac7
Create Date: 2025-05-16 13:40:39.281712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '939e613fc2f4'
down_revision: Union[str, None] = 'aead1aa38ac7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
